### ISSUE TITLE
Job QA (PDF Generation)

### ISSUE THREAD

**Issue by SomeoneWeird** [printersystems/roadmap#2]
Similar to #1, we should automatically generate a PDF that lists all sets + models with checkboxes next to them. The end user would then print this out, and manually tick boxes when going through the QA process.

Stretch goal would be to allow custom branding on this.

eg.

```
**Voron 2.4**
Options:
  - Hotend: Dragon
  - Size: 300
 
Models:
  - [ ] exhaust_filter_grill.stl
  - [ ] exhaust_filter_housing.stl
  - [ ] exhaust_filter_housing.stl

```
